name: MCA Scraper
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: pip install selenium beautifulsoup4 supabase
          
      - name: Run scraper
        env:
          WORKFORCE_COOKIES_B64: ${{ secrets.WORKFORCE_COOKIES_B64 }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          ls -la scripts/
          cd scripts/
          pwd
          python mca_scraper.py
