name: MCA Scraper
on:
  schedule:
    - cron: '0 9 * * 1-5'  # Weekdays at 9 AM
  workflow_dispatch:  # Manual trigger button

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: pip install selenium beautifulsoup4
        
      - name: Run scraper
        env:
          WORKFORCE_SESSION_COOKIES: ${{ secrets.WORKFORCE_SESSION_COOKIES }}
          SCRAPER_MODE: production
        run: python cookie_extractor.py
