name: MCA Scraper
on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4 supabase
          
      - name: Debug - List files
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Root directory contents ==="
          ls -la
          echo "=== Scripts directory contents ==="
          ls -la scripts/
          echo "=== Python path test ==="
          python -c "import sys; print('Python path:', sys.path)"
          
      - name: Run scraper
        env:
          WORKFORCE_COOKIES_B64: ${{ secrets.WORKFORCE_COOKIES_B64 }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: python scripts/mca_scraper.py
